spring:
  security:
    user:
      name: admin
      password: 123456
      roles:
        - user
        - admin
  datasource:
    url: jdbc:mysql://localhost:3306/jwb
    username: root
    password: 023017lys
    driver-class-name: com.mysql.cj.jdbc.Driver